<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Lengkap_input-113</name>
   <tag></tag>
   <elementGuidId>cae27ac1-0d11-430e-807b-2dc7171800fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-113</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-113']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>85ea742f-cbaf-4787-b906-1ee6cc9a0361</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-113</value>
      <webElementGuid>d4d15989-f142-42aa-8b0b-65f49c926518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d8bbdee5-e7b2-400f-b640-f72bcadff6db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-113&quot;)</value>
      <webElementGuid>51df0de1-9c93-415f-967d-34ee8a1d1e51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-113']</value>
      <webElementGuid>6357feb6-5ad5-4527-9e58-7ced44c7fbd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div/div/div/div/input</value>
      <webElementGuid>7a6ee0b9-0cd2-48bf-8fed-3c9a0d846106</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>bec8fd46-b5c3-424d-aa24-9dc05ff77897</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-113' and @type = 'text']</value>
      <webElementGuid>abed6963-eb7a-4ab6-9d9c-ecf4c9fa1c90</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
