<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_input-116</name>
   <tag></tag>
   <elementGuidId>49b1e09b-aa5f-4507-acf1-263e750e2da7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-116</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-116']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9da14766-d00f-4751-a75d-b4377cf67ef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-116</value>
      <webElementGuid>7a3bf6c5-85ea-4634-af55-1a939c06b3f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0c77ce90-9915-4244-bd6d-aef2e73236f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-116&quot;)</value>
      <webElementGuid>b8406004-9d72-4f03-b952-25a3318d3054</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-116']</value>
      <webElementGuid>fac43320-1d91-4615-950b-dd3ead7a9029</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div[2]/div/div/div/input</value>
      <webElementGuid>7675f2aa-9367-4a03-905a-94210f8eec5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>47a5d5e4-36d5-4742-8452-8e445ecf190c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-116' and @type = 'text']</value>
      <webElementGuid>29e3bd11-1fd9-4891-975e-95c7503b178c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
