<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_input-119</name>
   <tag></tag>
   <elementGuidId>63d78aba-1efc-4e24-b10e-4175d897f138</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-119</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-119']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ac87ba2a-a91b-4c17-9c11-3d5130c13064</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-119</value>
      <webElementGuid>3cd3d50f-b0c6-4d10-9e6d-0926137f459f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ed264504-6507-4909-a475-c65fc493277c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-119&quot;)</value>
      <webElementGuid>be772809-c17d-4a5d-9b0c-4d2826e70097</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-119']</value>
      <webElementGuid>3b56f385-bf7a-47d7-ae47-4be1e5d1ccdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div[3]/div/div/div/input</value>
      <webElementGuid>2e71829b-4e36-4737-ba84-e26c7216a175</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/input</value>
      <webElementGuid>aacdfed1-8758-4675-9f48-cb60447a7697</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-119' and @type = 'text']</value>
      <webElementGuid>8a4829f4-6833-4337-8ff1-f4d82902b673</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
