<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_5</name>
   <tag></tag>
   <elementGuidId>247e037e-c917-400f-8434-ed1cd7659442</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#list-item-35-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='list-item-35-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a85cba1e-3d85-4e78-82f6-7c1e8fbdb5b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8aae4891-8aa0-4ae2-98f8-64be4e7e97bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9e8f57cf-8599-478a-b11d-5319119c218d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>list-item-35-0</value>
      <webElementGuid>396ee581-edb3-423d-b21b-96e33310090d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>8a03c0b2-a9b7-434e-9fa7-0a0b13406006</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-list-item v-list-item--link theme--light</value>
      <webElementGuid>3615674e-27b2-4a49-8cd2-05b267f20d2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>3df9fe5e-8ddc-4233-9206-0dc2f90ceefc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list-item-35-0&quot;)</value>
      <webElementGuid>f21f46e2-d60d-4dac-b1af-62de527414c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='list-item-35-0']</value>
      <webElementGuid>7285447d-f516-4880-80b3-da0809a6fedf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list-26']/div</value>
      <webElementGuid>df74acd9-a89e-44c4-b1f4-bcce91631c5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refined Concrete Sausages'])[1]/following::div[17]</value>
      <webElementGuid>cb19dcdd-4d3a-4223-b932-7da30f021920</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[1]/preceding::div[9]</value>
      <webElementGuid>432f236c-629b-476f-abc1-2f937e371c34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'list-item-35-0', '&quot;', ')')])[1]/preceding::div[12]</value>
      <webElementGuid>45e3871b-fe8d-4a84-befe-70b1ec101498</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div</value>
      <webElementGuid>8affcde0-024b-4a44-9744-904dbbc94643</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'list-item-35-0' and (text() = '5' or . = '5')]</value>
      <webElementGuid>200dd9f6-55d4-44f6-8b10-b9f84e08071a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
