<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_input-102</name>
   <tag></tag>
   <elementGuidId>848091ee-0d2a-4657-93cf-800d3c99ee04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-102</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-102']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c1874c0f-3659-490c-9cc5-4306d9347969</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-102</value>
      <webElementGuid>4d81f13c-79c0-4c2c-acf1-c0b970b2aa84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7be28137-3984-4531-9224-453734765476</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-102&quot;)</value>
      <webElementGuid>ba601a30-af3f-41d2-b7c8-80b4fcc167a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-102']</value>
      <webElementGuid>e00d3ebe-72ce-47ec-af46-3cee41a39cea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div/div/div/div/input</value>
      <webElementGuid>7ed969d0-963c-4684-9b85-f8f1b0d02eb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>d44aaa66-9042-4883-9b00-96b4b05d7909</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-102' and @type = 'text']</value>
      <webElementGuid>8936d539-ef37-419d-a227-a52c4e6b26d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
