<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_input-105</name>
   <tag></tag>
   <elementGuidId>a45f2c08-374d-4a1e-b5e3-2dfa0cd246f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-105</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-105']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7f8a577b-2a10-410e-904b-40302aa30c78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-105</value>
      <webElementGuid>66e5fce3-90ab-4ff1-94af-1411beb8fe11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>56b4f722-7fab-4852-966b-00f1ad3ac571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-105&quot;)</value>
      <webElementGuid>a8e63679-4dbf-4f40-b66e-b27d4d6b9a81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-105']</value>
      <webElementGuid>d2fdd970-a206-4748-a71d-4d3b57c848db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div[2]/div/div/div/input</value>
      <webElementGuid>f9fba38a-de44-4b63-8d97-b8fad31bdb3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>393ad54a-1093-492f-823f-37e9a54f6e01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-105' and @type = 'text']</value>
      <webElementGuid>79f63b4d-a264-4f9d-bda3-b1407e1300d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
