<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_input-102</name>
   <tag></tag>
   <elementGuidId>95af6e7b-9cbe-4c40-94b7-20e4f02edd5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-102</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-102']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1d218adb-1676-4d4d-8a69-bdeb1a57f0bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-102</value>
      <webElementGuid>cfdebd14-98c8-434b-a999-fc90bfa5cc0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>563977a1-5e82-451e-a4e4-a8e9284c3c9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-102&quot;)</value>
      <webElementGuid>1533853f-aece-4e46-9798-9824f80310d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-102']</value>
      <webElementGuid>b1c6c69f-a06c-484f-a251-e232f9c94e57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div/div/div/div/input</value>
      <webElementGuid>1c877439-7438-4da0-87e5-f3a3d3f425d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>4b5f1bca-b5de-4e05-954b-d15b2796afe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-102' and @type = 'text']</value>
      <webElementGuid>3a0ac9e2-bbaa-4d54-9bf5-8a45c5cd707b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
