<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_input-105</name>
   <tag></tag>
   <elementGuidId>768e1508-1f01-4f3b-a758-7270ec96d14a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-105</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-105']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3d490475-a4ef-472c-ba0d-5d6d4da811e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-105</value>
      <webElementGuid>5146a35c-de82-4008-9352-15409e9eddc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7761bacb-5d4d-4672-9bdc-bd5cd28857e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-105&quot;)</value>
      <webElementGuid>0400a528-cb25-4c7e-b68c-1eb2280dfbb7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-105']</value>
      <webElementGuid>2e495df1-6f85-49ab-84de-0d2e8bbe7f63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div[2]/div/div/div/input</value>
      <webElementGuid>0cd09e0b-83a4-4ef2-80fd-e409a22e8cfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>07b7f91f-538f-42bb-a30c-9085e91d7793</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-105' and @type = 'text']</value>
      <webElementGuid>ec52ed97-face-481b-bd06-962a04da72b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
