<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_input-70</name>
   <tag></tag>
   <elementGuidId>497c3d92-df72-48a9-b55e-b280cf51026b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-70</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-70']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c31ac89d-6d32-4bfe-9a3a-9a1e3a7dad6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-70</value>
      <webElementGuid>e1a934c3-a714-40aa-a148-5a678a010907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>419b04a6-de8f-47ae-823e-e4cb2648c4b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-70&quot;)</value>
      <webElementGuid>49fbe9b3-4f09-4cb8-9114-1e482a72274e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-70']</value>
      <webElementGuid>f502c717-d5aa-4000-a139-f452658ee7a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div[2]/div/div/div/input</value>
      <webElementGuid>9228e4ac-a23a-4095-9b36-dc656c397676</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>1bc0a50f-3a35-4dda-8fcb-a5179ed5895d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-70' and @type = 'text']</value>
      <webElementGuid>5a5b20c6-d4f8-4b91-9884-9cb20eb96182</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
