<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_input-67</name>
   <tag></tag>
   <elementGuidId>4385ca47-f6c1-47f2-8620-08dacb791c3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-67</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-67']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a71b104d-39ab-4caf-be53-a6e36c0740f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-67</value>
      <webElementGuid>f0e1958f-c42d-4679-9041-c7bc3e742b0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c69ff66d-48bb-4927-8480-0456119a1498</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-67&quot;)</value>
      <webElementGuid>c0287112-f29d-47bb-a8f1-8f64fb699b0f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-67']</value>
      <webElementGuid>ca4ca016-8fd7-4eff-9fd7-437e589ce8cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div/div/div/div/input</value>
      <webElementGuid>1693fab6-ab32-4536-8ca8-02d97544816b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>de18de30-9baa-4453-bbee-094e07739ef6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-67' and @type = 'text']</value>
      <webElementGuid>416c0aa3-f57d-4e08-b078-3356ced582d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
